import swaggerJsdoc from "swagger-jsdoc";
import type { OAS3Options } from "swagger-jsdoc";

const options: OAS3Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Multi-Branch POS System API",
      version: "1.0.0",
      description:
        "Complete API documentation for the multi-branch Point of Sale system with inventory management, staff assignments, and customer tracking.",
      contact: {
        name: "API Support",
        email: "support@example.com",
      },
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Development server",
      },
      {
        url: "https://api.production.com",
        description: "Production server",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Enter your JWT token",
        },
      },
      parameters: {
        tenantId: {
          name: "X-Tenant-ID",
          in: "header",
          required: true,
          schema: {
            type: "string",
          },
          description: "Tenant identifier",
        },
        branchId: {
          name: "X-Branch-ID",
          in: "header",
          required: false,
          schema: {
            type: "string",
          },
          description: "Branch identifier (optional)",
        },
      },
      schemas: {
        Error: {
          type: "object",
          properties: {
            success: {
              type: "boolean",
              example: false,
            },
            error: {
              type: "object",
              properties: {
                message: {
                  type: "string",
                  example: "Error description",
                },
                code: {
                  type: "string",
                  example: "ERROR_CODE",
                },
                details: {
                  type: "object",
                },
              },
            },
          },
        },
        ShopSettings: {
          type: "object",
          properties: {
            id: { type: "string" },
            companyName: { type: "string" },
            tradingName: { type: "string" },
            vatNumber: { type: "string" },
            tinNumber: { type: "string" },
            businessRegistrationNumber: { type: "string" },
            defaultTaxRate: { type: "number" },
            addressLine1: { type: "string" },
            addressLine2: { type: "string" },
            city: { type: "string" },
            stateProvince: { type: "string" },
            postalCode: { type: "string" },
            country: { type: "string" },
            phoneNumber: { type: "string" },
            alternativePhone: { type: "string" },
            email: { type: "string" },
            faxNumber: { type: "string" },
            website: { type: "string" },
            defaultCurrency: { type: "string" },
            defaultTimezone: { type: "string" },
            logoUrl: { type: "string" },
            defaultReceiptHeader: { type: "string" },
            defaultReceiptFooter: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Branch: {
          type: "object",
          properties: {
            id: { type: "string" },
            code: { type: "string" },
            name: { type: "string" },
            managerId: { type: "string" },
            isActive: { type: "boolean" },
            useShopVat: { type: "boolean" },
            useShopTin: { type: "boolean" },
            useShopAddress: { type: "boolean" },
            addressLine1: { type: "string" },
            city: { type: "string" },
            phoneNumber: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Product: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            sku: { type: "string" },
            barcode: { type: "string" },
            categoryId: { type: "string" },
            categoryName: { type: "string" },
            description: { type: "string" },
            price: { type: "number" },
            cost: { type: "number" },
            unit: { type: "string" },
            imageUrl: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ProductCategory: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            description: { type: "string" },
            parentId: { type: "string" },
            isDefault: { type: "boolean" },
            detail: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Inventory: {
          type: "object",
          properties: {
            id: { type: "string" },
            productId: { type: "string" },
            productName: { type: "string" },
            productSku: { type: "string" },
            unit: { type: "string" },
            quantity: { type: "number" },
            minimumStock: { type: "number" },
            maximumStock: { type: "number" },
            lastRestocked: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        InventoryTransfer: {
          type: "object",
          properties: {
            id: { type: "string" },
            productId: { type: "string" },
            productName: { type: "string" },
            fromBranchId: { type: "string" },
            fromBranchName: { type: "string" },
            toBranchId: { type: "string" },
            toBranchName: { type: "string" },
            quantity: { type: "number" },
            status: {
              type: "string",
              enum: ["pending", "approved", "rejected", "completed"],
            },
            notes: { type: "string" },
            requestedBy: { type: "string" },
            approvedBy: { type: "string" },
            requestedAt: { type: "string", format: "date-time" },
            approvedAt: { type: "string", format: "date-time" },
            completedAt: { type: "string", format: "date-time" },
          },
        },
        Customer: {
          type: "object",
          properties: {
            id: { type: "string" },
            firstName: { type: "string" },
            lastName: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            address: { type: "string" },
            dateOfBirth: { type: "string", format: "date-time" },
            loyaltyPoints: { type: "number" },
            lastPurchaseAt: { type: "string", format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Currency: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string", example: "USD" },
            symbol: { type: "string", example: "$" },
            exchangeRate: { type: "number", example: 1.0 },
            isDefault: { type: "boolean" },
            detail: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        PaymentMethod: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string", example: "Cash" },
            isDefault: { type: "boolean" },
            detail: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        BranchPaymentMethod: {
          type: "object",
          properties: {
            id: { type: "string" },
            branchId: { type: "string" },
            paymentMethodId: { type: "string" },
            name: { type: "string" },
            detail: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Supplier: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            phone: { type: "string" },
            email: { type: "string" },
            address: { type: "string" },
            vatNumber: { type: "string" },
            tinNumber: { type: "string" },
            contactPerson: { type: "string" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Tax: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string", example: "VAT" },
            taxRate: { type: "number", example: 15.0 },
            taxCode: { type: "string", example: "VAT001" },
            taxID: { type: "string", example: "EXT-TAX-12345" },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        StockTake: {
          type: "object",
          properties: {
            id: { type: "string" },
            branchId: { type: "string" },
            branchName: { type: "string" },
            status: {
              type: "string",
              enum: ["initialized", "started", "counted", "approved", "rejected"],
              example: "started"
            },
            createdBy: { type: "string" },
            startedBy: { type: "string" },
            countedBy: { type: "string" },
            approvedBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            startedAt: { type: "string", format: "date-time" },
            countedAt: { type: "string", format: "date-time" },
            approvedAt: { type: "string", format: "date-time" },
            rejectionNotes: { type: "string" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        StockTakeItem: {
          type: "object",
          properties: {
            id: { type: "string" },
            stockTakeId: { type: "string" },
            productId: { type: "string" },
            productName: { type: "string" },
            productSku: { type: "string" },
            unit: { type: "string" },
            expectedQuantity: { type: "number", example: 100 },
            actualQuantity: { type: "number", example: 95 },
            variance: { type: "number", example: -5 },
            notes: { type: "string", example: "5 damaged units found" },
            countedBy: { type: "string" },
            countedAt: { type: "string", format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Purchase: {
          type: "object",
          properties: {
            id: { type: "string" },
            poNumber: { type: "string", example: "PO2025-00001" },
            branchId: { type: "string" },
            supplierId: { type: "string" },
            purchaseDate: { type: "string", format: "date-time" },
            expectedDeliveryDate: { type: "string", format: "date-time" },
            actualDeliveryDate: { type: "string", format: "date-time" },
            invoiceNumber: { type: "string" },
            notes: { type: "string" },
            subtotal: { type: "number" },
            shippingCost: { type: "number" },
            taxApplied: { type: "boolean" },
            taxAmount: { type: "number" },
            total: { type: "number" },
            amountPaid: { type: "number" },
            amountDue: { type: "number" },
            status: {
              type: "string",
              enum: ["draft", "submitted", "partially_paid", "fully_paid", "received"]
            },
            createdBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Sale: {
          type: "object",
          properties: {
            id: { type: "string" },
            invoiceNumber: { type: "string", example: "INV2025-00001" },
            branchId: { type: "string" },
            branchName: { type: "string" },
            customerId: { type: "string" },
            customerName: { type: "string" },
            saleType: { type: "string", enum: ["credit", "till"], example: "credit" },
            saleDate: { type: "string", format: "date-time" },
            subtotal: { type: "number" },
            discountAmount: { type: "number" },
            taxMode: { type: "string", enum: ["inclusive", "exclusive"] },
            taxRate: { type: "number" },
            taxAmount: { type: "number" },
            total: { type: "number" },
            amountPaid: { type: "number" },
            amountDue: { type: "number" },
            status: {
              type: "string",
              enum: ["draft", "confirmed", "partially_paid", "fully_paid", "delivered", "completed"],
              example: "confirmed"
            },
            notes: { type: "string" },
            createdBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Quotation: {
          type: "object",
          properties: {
            id: { type: "string" },
            quotationNumber: { type: "string", example: "QT2025-00001" },
            branchId: { type: "string" },
            branchName: { type: "string" },
            customerId: { type: "string" },
            customerName: { type: "string" },
            quotationDate: { type: "string", format: "date-time" },
            validityDays: { type: "number", example: 30 },
            expiryDate: { type: "string", format: "date-time" },
            subtotal: { type: "number" },
            discountAmount: { type: "number" },
            taxAmount: { type: "number" },
            total: { type: "number" },
            status: {
              type: "string",
              enum: ["draft", "sent", "accepted", "rejected", "expired"],
              example: "sent"
            },
            convertedToSaleId: { type: "string" },
            convertedToLaybyId: { type: "string" },
            notes: { type: "string" },
            createdBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Layby: {
          type: "object",
          properties: {
            id: { type: "string" },
            laybyNumber: { type: "string", example: "LB2025-00001" },
            branchId: { type: "string" },
            branchName: { type: "string" },
            customerId: { type: "string" },
            customerName: { type: "string" },
            laybyDate: { type: "string", format: "date-time" },
            subtotal: { type: "number" },
            discountAmount: { type: "number" },
            taxAmount: { type: "number" },
            total: { type: "number" },
            depositRequired: { type: "number" },
            amountPaid: { type: "number" },
            amountDue: { type: "number" },
            status: {
              type: "string",
              enum: ["draft", "active", "partially_paid", "fully_paid", "collected", "cancelled"],
              example: "active"
            },
            cancellationFee: { type: "number" },
            cancellationReason: { type: "string" },
            notes: { type: "string" },
            createdBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        Payment: {
          type: "object",
          properties: {
            id: { type: "string" },
            receiptNumber: { type: "string", example: "RCP2025-00001" },
            amount: { type: "number" },
            currencyId: { type: "string" },
            currencyName: { type: "string" },
            currencySymbol: { type: "string" },
            paymentMethodId: { type: "string" },
            paymentMethodName: { type: "string" },
            exchangeRate: { type: "number" },
            amountInBaseCurrency: { type: "number" },
            referenceNumber: { type: "string" },
            paymentDate: { type: "string", format: "date-time" },
            notes: { type: "string" },
            createdBy: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        BranchDiscount: {
          type: "object",
          properties: {
            id: { type: "string" },
            branchId: { type: "string" },
            name: { type: "string", example: "Senior Citizen" },
            percentage: { type: "number", example: 10 },
            isActive: { type: "boolean" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        TenantSettings: {
          type: "object",
          properties: {
            id: { type: "string" },
            tenantId: { type: "string" },
            quotationValidityDays: { type: "number", example: 30 },
            taxMode: { type: "string", enum: ["inclusive", "exclusive"], example: "exclusive" },
            taxRate: { type: "number", example: 15 },
            laybyFee: { type: "number", example: 0 },
            cancellationFee: { type: "number", example: 50 },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        BranchSettings: {
          type: "object",
          properties: {
            id: { type: "string" },
            branchId: { type: "string" },
            quotationValidityDays: { type: "number" },
            laybyDeposit: { type: "number" },
            cancellationFee: { type: "number" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
    tags: [
      {
        name: "Authentication",
        description: "Authentication and authorization endpoints",
      },
      {
        name: "Shop Settings",
        description: "Tenant-wide business configuration",
      },
      {
        name: "Branches",
        description: "Branch management with settings inheritance",
      },
      {
        name: "Staff",
        description: "Staff assignment and transfers",
      },
      {
        name: "Products",
        description: "Product catalog and categories",
      },
      {
        name: "Inventory",
        description: "Inventory management and stock tracking",
      },
      {
        name: "Stock Takes",
        description: "Physical inventory counts with multi-stage approval workflow",
      },
      {
        name: "Purchases",
        description: "Supplier purchase orders with multi-currency payments and goods receiving",
      },
      {
        name: "Sales",
        description: "Credit sales and till sales with multi-currency payments",
      },
      {
        name: "Quotations",
        description: "Sales quotations with validity period and conversion to sales/laybys",
      },
      {
        name: "Laybys",
        description: "Layaway sales with deposit requirement and stock reservation",
      },
      {
        name: "Sales Settings",
        description: "Tenant and branch sales settings, discounts management",
      },
      {
        name: "Transfers",
        description: "Inter-branch inventory transfers",
      },
      {
        name: "Customers",
        description: "Customer management",
      },
      {
        name: "Currencies",
        description: "Currency management with exchange rates",
      },
      {
        name: "Payment Methods",
        description: "Tenant-wide and branch-specific payment methods",
      },
      {
        name: "Suppliers",
        description: "Supplier management",
      },
      {
        name: "Taxes",
        description: "Tax management and product tax assignments",
      },
      {
        name: "Users",
        description: "User management",
      },
      {
        name: "Tenants",
        description: "Tenant management (SuperAdmin only)",
      },
    ],
  },
  apis: ["./src/features/**/*.routes.ts", "./src/app.ts"],
};

export const swaggerSpec = swaggerJsdoc(options);
